@baseUrl = http://localhost:8080/api

### Create Playsite
POST {{baseUrl}}/v1/playsites
Content-Type: application/json

{
  "name": "Playsite 1"
}

> {%
    client.global.set("playsite1", response.body.id);
%}

### Create Attractions
POST {{baseUrl}}/v1/attractions
Content-Type: application/json

[
  {
    "name": "Swing",
    "maxCapacity": 1
  },
  {
    "name": "Carousel",
    "maxCapacity": 1
  },
  {
    "name": "Slide",
    "maxCapacity": 1
  }
]

> {%
    client.global.set("attractions", response.body);
%}

### Add attractions to playsite
< {%
    const attractions = client.global.get("attractions");

    let allAttractions = [];
    for (let i = 0; i < attractions.length; i++) {
        allAttractions.push({
            attractionId: attractions[i].id,
            amount: 1
        });
    }

    request.variables.set("attractionsWithAmounts", JSON.stringify(allAttractions))
%}
POST {{baseUrl}}/v1/playsites/{{playsite1}}/attractions
Content-Type: application/json


{{attractionsWithAmounts}}

### Get Playsite info
GET {{baseUrl}}/v1/playsites/{{playsite1}}

### Create customer 1
POST {{baseUrl}}/v1/customers
Content-Type: application/json

{
  "name": "John",
  "age": 18
}

> {%
    client.global.set("customer1", response.body.ticketNumber);
%}

### Create customer 2
POST {{baseUrl}}/v1/customers
Content-Type: application/json

{
  "name": "Michael",
  "age": 25
}

> {%
    client.global.set("customer2", response.body.ticketNumber);
%}

### Create customer 3
POST {{baseUrl}}/v1/customers
Content-Type: application/json

{
  "name": "Bob",
  "age": 60
}

> {%
    client.global.set("customer3", response.body.ticketNumber);
%}

### Create customer 4
POST {{baseUrl}}/v1/customers
Content-Type: application/json

{
  "name": "Larry",
  "age": 40
}

> {%
    client.global.set("customer4", response.body.ticketNumber);
%}

### Create customer 5
POST {{baseUrl}}/v1/customers
Content-Type: application/json

{
  "name": "Diana",
  "age": 30
}

> {%
    client.global.set("customer5", response.body.ticketNumber);
%}

### Add customer 1 to playsite
POST {{baseUrl}}/v1/playsites/{{playsite1}}/customers/{{customer1}}?waitInQueue=true

### Add customer 2 to playsite
POST {{baseUrl}}/v1/playsites/{{playsite1}}/customers/{{customer2}}?waitInQueue=true

### Add customer 3 to playsite
POST {{baseUrl}}/v1/playsites/{{playsite1}}/customers/{{customer3}}?waitInQueue=true

### Add customer 4 to playsite (Should be added to queue)
POST {{baseUrl}}/v1/playsites/{{playsite1}}/customers/{{customer4}}?waitInQueue=true

### Get Playsite info
GET {{baseUrl}}/v1/playsites/{{playsite1}}

### Add customer 5 to playsite (Should be rejected)
POST {{baseUrl}}/v1/playsites/{{playsite1}}/customers/{{customer5}}?waitInQueue=false

### Remove customer 1 from playsite
DELETE {{baseUrl}}/v1/playsites/{{playsite1}}/customers/{{customer1}}

### Get Playsite info
GET {{baseUrl}}/v1/playsites/{{playsite1}}

### Get total visitor count
GET {{baseUrl}}/v1/playground/visitors




