@baseUrl = http://localhost:8080/api

### Create Playsite
POST {{baseUrl}}/v1/playsites
Content-Type: application/json

{
  "name": "Test play site"
}

> {%
    client.global.set("newPlaysiteId", response.body.id);
%}

### Update Playsite
PUT {{baseUrl}}/v1/playsites/{{newPlaysiteId}}
Content-Type: application/json

{
  "name": "Test play site - The Ultimate"
}

### Get Playsite
GET {{baseUrl}}/v1/playsites/{{newPlaysiteId}}

### Get Playsite info
GET {{baseUrl}}/v1/playsites/1/info

### Get all playsites
GET {{baseUrl}}/v1/playsites

### Delete playsite
DELETE {{baseUrl}}/v1/playsites/{{newPlaysiteId}}

### Try to create invalid Playsite
POST {{baseUrl}}/v1/playsites
Content-Type: application/json

{
  "name": ""
}


