CREATE TABLE playsite
(
    id   bigint generated by default as identity PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE attraction
(
    id           bigint generated by default as identity PRIMARY KEY,
    name         varchar(255),
    max_capacity int,
    CONSTRAINT chk_max_capacity_positive CHECK (max_capacity > 0)
);

CREATE TABLE customer
(
    id   varchar(36) PRIMARY KEY,
    name varchar(255),
    age  int
);

CREATE TABLE playsite_attractions
(
    playsite   bigint,
    attraction bigint,
    amount int,
    PRIMARY KEY (playsite, attraction),
    CONSTRAINT chk_amount_positive CHECK (amount > 0),
    CONSTRAINT fk_playsite_attraction_playsite FOREIGN KEY (playsite) REFERENCES playsite (id),
    CONSTRAINT fk_playsite_attraction_attraction FOREIGN KEY (attraction) REFERENCES attraction (id)
);

CREATE TABLE playsite_customers
(
    playsite bigint,
    customer varchar(36),
    PRIMARY KEY (playsite, customer),
    CONSTRAINT fk_playsite_customer_playsite FOREIGN KEY (playsite) REFERENCES playsite (id),
    CONSTRAINT fk_playsite_customer_customer FOREIGN KEY (customer) REFERENCES customer (id)
);

CREATE TABLE playsite_queue
(
    playsite bigint,
    customer varchar(36),
    PRIMARY KEY (playsite, customer),
    CONSTRAINT fk_playsite_queue_playsite FOREIGN KEY (playsite) REFERENCES playsite (id),
    CONSTRAINT fk_playsite_queue_customer FOREIGN KEY (customer) REFERENCES customer (id)
);



